### ISSUE TITLE
Trying with existing FA install

### ISSUE THREAD

**Issue by srstactical** [frontaccounting/faplanet#1]
Hi,
I would like to give this a try and see how it goes. I have downloaded and installed on my server.

When I log in I get the following error:-
× DATABASE ERROR : Cannot load menu from the database.
error code : 1146
error message : Table 'fa5172usL.0_menu' doesn't exist
sql that failed was : SELECT \* FROM 0_menu WHERE menu='default'

There is obviously a missing table in the database. Can you let me have the table layout etc so I can set this up.

Thanks

Steve

**Comment by frontaccounting** [comment]
I updated the menu files, you can copy the sql code or redo install. thx for reporting.

**Comment by frontaccounting** [comment]
The code is on master.

**Comment by srstactical** [comment]
Many thanks. I also found a missing file.... sales/manage/search_customers.php.

Steve

**Comment by frontaccounting** [comment]
No problem, I hope you like it. Cheers!

**Comment by srstactical** [comment]
There appears to be a file missing....... sales/manage/search_customers.php.
From Menu, Sales, Customer
Steve

**Comment by frontaccounting** [comment]
It should be there on master already, it went missing in the previous commit.

**Comment by srstactical** [comment]
It's there... Thank you!
Steve
